import type { Metadata } from "next";
import "@/styles/globals.css";
import TopNavigation from "@/components/Navigation/TopNavigation/TopNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopNavigation>{children}</TopNavigation>
      </body>
    </html>
  );
}
