import type { Metadata } from "next";
import "@/styles/globals.css";
import MobileSideBar from "@/components/Navigation/MobileSideBar/MobileSideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <TopNavigation>{children}</TopNavigation> */}
        <MobileSideBar>{children}</MobileSideBar>
      </body>
    </html>
  );
}
